### ISSUE TITLE
Export problem

### ISSUE THREAD

**Issue by Trinitas** [keverw/node_CloudFlare#1]
Is it possible to access this by module.exports somehow ?

**Comment by keverw** [comment]
Are you still having this issue? It should of been exporting all along.

**Comment by Trinitas** [comment]
I got it to work but i haven't used it in one year. How is the project going? Is it still usable? Cloudflare has had mayor updates but not this one

**Comment by keverw** [comment]
Oh wow, fast reply. The update I just did worked or you got it working from before?

Also it seems to still be working, I just had to update the IPs as they were a bit outdated compared to what CloudFlare is using now.

**Comment by Trinitas** [comment]
I got it to work one year ago. I may test it later!

**Comment by keverw** [comment]
Okay, thanks! I readded the (function () part then since that didn't seem to be causing issues.

I been out of the Node.js world for a while, so just been trying to update all my modules where people filed issues.
